[template.environment]
  MEDUSA_BACKEND_URL="https://harbour-clothing-server-production.up.railway.app/"

[build]
  publish = "public/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"